### ISSUE TITLE
Update JEA from 1.1 to current

### ISSUE THREAD

**Issue by DebbyParker** [JoomlaEstateAgency/com_jea#15]
It was working so why change right?
Well now because I have to upgrade the site to work with php7.2 or later from php5.4 I have to upgrade my site from joomla 1.5.22 to current version but need to upgrade JEA from v.1.1 to current.  Can you either tell me the proper steps to do this or point me in the right direction?

**Comment by ilhooq** [comment]
You have to upgrade your website to Joomla 2.x and install this [release of JEA](https://github.com/JoomlaEstateAgency/com_jea/releases/tag/com_jea-2.30).

Then use the import tool in JEA to import from 1.x to 2.x

After that, upgrade to Joomla 3.x and to the last release of JEA.
