### ISSUE TITLE
Is there a plan for Joomla 4 ?

### ISSUE THREAD

**Issue by fabrice-dresscodes** [JoomlaEstateAgency/com_jea#17]
Hello,

We are using the current version of JEA for Joomla 3.

I was wondering if there is a plan for Joomla 4 scheduled ?

Otherwise, could you advice a similar plugin ? 

Thanks,

**Comment by BIT-Michael** [comment]
Same Question ..
What about JEA and Joomla 4
an update would be great !!

thanks and merci

**Comment by ilhooq** [comment]
There is no plan for now (I'm working on other projects) but if you want to contribute to migrate JEA on Joomla 4, you are welcome

**Comment by Toolmaster** [comment]
Same question here... Will there be a Joomla 4 version?

**Comment by ilhooq** [comment]
@Toolmaster  : Yes but there is no official release for now. You can try to install the [master zip](https://github.com/JoomlaEstateAgency/com_jea/archive/refs/heads/master.zip). It should work on Joomla 4.

**Comment by Toolmaster** [comment]
Any news on this? Is there a working Joomla 4 version that has been confirmed?

**Comment by ilhooq** [comment]
There is a working Joomla 4 version. Look at the releases : https://github.com/JoomlaEstateAgency/com_jea/releases
