### ISSUE TITLE
property detail click error

### ISSUE THREAD

**Issue by rnervi** [JoomlaEstateAgency/com_jea#27]
j4.3.4
property list in the content area
click on one
500 Layout default_squeezebox not found

**Comment by rnervi** [comment]
this seems the line invoking the JS

(file: /web/components/com_jea/views/property/default.php)

<?php if (!empty($this->row->images)) echo $this->loadTemplate($this->params->get('images_layout', 'squeezebox')) ?>

the .js is in the media folder. sounds like it cannot load or wrong path

**Comment by rnervi** [comment]
have the line removed opens the property but the images. 
this confirm the line is not founding the  layout for images
we wait for a fix, ty

**Comment by rnervi** [comment]
more on.
goto backoffice
component -> jea -> options
change the param for "property display" tab
from "classical" to "magnific" then the error changes to :
Call to a member function get() on null

**Comment by ilhooq** [comment]
Which version of JEA do you use ?

**Comment by rnervi** [comment]
Joomla Estate Agency 4.0.5

**Comment by rnervi** [comment]
![jea](https://github.com/JoomlaEstateAgency/com_jea/assets/43026419/84d63cec-dca2-4cdc-8453-14d86a55e692)

**Comment by rnervi** [comment]
installing & checking...

**Comment by ilhooq** [comment]
> j4.3.4 property list in the content area click on one 500 Layout default_squeezebox not found

The commit 91ef3fb should fix this error.

> from "classical" to "magnific" then the error changes to :
> _Call to a member function get() on null_
> forever

Can you set the `Error Reporting` to `Maximum` in _System > Global Configuration > Server_ in your backend and
`Debug System` to `Yes` in _System > Global Configuration > System_, then post the complete call stack of your error ?

**Comment by rnervi** [comment]
<html><body>


Call stack
--
# | Function | Location
1 | () | JROOT/plugins/captcha/recaptcha/src/Extension/ReCaptcha.php:98
2 | Joomla\Plugin\Captcha\ReCaptcha\Extension\ReCaptcha->onInit() |  
3 | call_user_func_array() | JROOT/libraries/src/Captcha/Captcha.php:215
4 | Joomla\CMS\Captcha\Captcha->update() | JROOT/libraries/src/Captcha/Captcha.php:118
5 | Joomla\CMS\Captcha\Captcha->initialise() | JROOT/libraries/src/Captcha/Captcha.php:143
6 | Joomla\CMS\Captcha\Captcha->display() | JROOT/components/com_jea/views/property/view.html.php:184
7 | JeaViewProperty->displayCaptcha() | JROOT/components/com_jea/views/property/tmpl/default_contactform.php:76
8 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:410
9 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/components/com_jea/views/property/tmpl/default.php:257
10 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:410
11 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:203
12 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/components/com_jea/views/property/view.html.php:113
13 | JeaViewProperty->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:645
14 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_jea/controllers/default.php:93
15 | JeaControllerDefault->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:678
16 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_jea/jea.php:27
17 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
18 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
19 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
20 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
21 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
22 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
23 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
24 | require_once() | JROOT/index.php:32


</body>
</html>

**Comment by ilhooq** [comment]
The issue is relative to the captcha. This 0e68e2a should fix it.
