### ISSUE TITLE
Error 500 - behavior::modal not found - property detail click error

### ISSUE THREAD

**Issue by Toolmaster** [JoomlaEstateAgency/com_jea#28]
After JEA update to version 4.0.5 (from 3.X) it is not possible to click any properties without getting this error: 500 behavior::modal not found
Joomla 4.3 and using the YooTheme PRO Page Builder template.

There is also a database problem it seems as the database is version 4.0 but I Joomla database maintenance says the manifest version is 4.0.5. I don't know if this is related or even a real error however.

**Comment by ilhooq** [comment]
Can you set the Error Reporting to Maximum in System > Global Configuration > Server in your backend and
Debug System to Yes in System > Global Configuration > System, then post the complete call stack of your error ?

**Comment by Toolmaster** [comment]
Call stack
--
# | Function | Location
1 | () | JROOT\libraries\src\HTML\HTMLHelper.php:141
2 | Joomla\CMS\HTML\HTMLHelper::_() | JROOT\components\com_jea\views\property\tmpl\default_squeezebox.php:50
3 | include() | JROOT\libraries\src\MVC\View\HtmlView.php:410
4 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT\components\com_jea\views\property\tmpl\default.php:49
5 | include() | JROOT\libraries\src\MVC\View\HtmlView.php:410
6 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT\libraries\src\MVC\View\HtmlView.php:203
7 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT\components\com_jea\views\property\view.html.php:113
8 | JeaViewProperty->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:645
9 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\components\com_jea\controllers\default.php:93
10 | JeaControllerDefault->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:678
11 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\components\com_jea\jea.php:27
12 | require_once() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:71
13 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:73
14 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:361
15 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\SiteApplication.php:208
16 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT\libraries\src\Application\SiteApplication.php:249
17 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:293
18 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\includes\app.php:61
19 | require_once() | JROOT\index.php:32

**Comment by Toolmaster** [comment]
This worked. Why keep to option in that does not work? Mootools have been goon for 5+ years?

**Comment by ilhooq** [comment]
This option has been removed in 3a04571
