### ISSUE TITLE
Fields Hewying Type and property type cannot be set.

### ISSUE THREAD

**Issue by petergehle** [JoomlaEstateAgency/com_jea#30]
The fields "type of hewing" and "property type" cannot be set, the last Item in the list is automatically used.
If I change it, it will be set back to the last Items of the Dropdown.

**Comment by ilhooq** [comment]
It appears to be a JavaScript bug. To see if it resolves the problem, could you please try installing the [JEA dev version](https://github.com/JoomlaEstateAgency/com_jea/archive/refs/heads/master.zip)? Before testing, make sure to refresh your browser cache.

**Comment by petergehle** [comment]
The Dev Version works.
