### ISSUE TITLE
Property edit page: Use tabs for extra attributes

### ISSUE THREAD

**Issue by venomdev** [JoomlaEstateAgency/com_jea#8]
I have started to test out the JEA component and thought the admin might be a bit more user friendly if some of the other editable attributes like adding pictures were under seperate tabs across the top like the edit article admin page.

I would be able to make the code changes myself, I'm kind of interested to know if it's wanted and would be accepted into master.

**Comment by ilhooq** [comment]
It's a good idea. It may be accepted into master after a pull request.
